### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by adamversed** [gtryf/Sitecore.Sitemap.Xml#3]
hi, I would like to make use of your sitemap project in a commercial project i am working on.  Is that ok?  Theres no license on the repo so thought I should check we have your permission?  If that is the case, could you please add a MIT or other appropriate licence to the repo.

cheers,

Adam

**Comment by gtryf** [comment]
Hi Adam,

Of course you have my permission. I licensed the repo under the MIT license so you are free to use the project as you wish. As a personal favour, I'd really like to know where the module has been used so once your project is launched, could you please send me the link? :)

(You can send it in a personal message if you wish)

Cheers,
George
